[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
; Aquí puedes definir variables globales si las necesitas en el futuro

; =========================================================
; CONTEXTO 1: LA POBLACIÓN (Extensiones 100 al 115)
; =========================================================
[poblacion]

; 1. Llamadas internas entre la población (100 al 115) CON FILTRO
; Eliminamos la regla duplicada arriba y dejamos esta que incluye el filtro
exten => _1XX,1,NoOp(Validando llamada de ${CALLERID(num)} a ${EXTEN})
same => n,AGI(validador_central1.py,${CALLERID(num)})
same => n,GotoIf($["${ES_SPAM}" = "SI"]?rechazar:permitir)
same => n(rechazar),Playback(privacy-incorrect)
same => n,Hangup()
same => n(permitir),Dial(PJSIP/${EXTEN},30)
same => n,Hangup()

; 2. Llamadas hacia la Central 1 (*111)
exten => *111,1,NoOp(El usuario ${CALLERID(num)} llama a la Central 1)
same => n,Answer()
same => n,AGI(validador_central1.py,${CALLERID(num)})
same => n,GotoIf($["${ES_SPAM}" = "SI"]?rechazar:permitir)
same => n(rechazar),Hangup()
same => n(permitir),Dial(PJSIP/200,30)
same => n,Hangup()

; 3. Llamadas hacia la Central 2 (*010)
exten => *010,1,NoOp(El usuario ${CALLERID(num)} entró al menú central)
same => n,Answer()
; IMPORTANTE: Pasamos el CallerID aquí para que el script sepa quién gestiona la lista
same => n,AGI(menu_central2.py,${CALLERID(num)})
same => n,Hangup()


; =========================================================
; CONTEXTO 2: LA CENTRAL 1
; =========================================================
[central-1]

; 1. Puede llamar a la población (100 al 115)
exten => _1XX,1,Dial(PJSIP/${EXTEN},30)
same => n,Hangup()

; 2. Regla para llamar a la Central 2 marcando *010
exten => *010,1,NoOp(Llamada desde Central 1 hacia Central 2)
same => n,Answer()
; IMPORTANTE: Pasamos el CallerID aquí también
same => n,AGI(menu_central2.py,${CALLERID(num)})
same => n,Hangup()
