[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0:5060
tcpenable=yes
transport=tls,udp,tcp
tcpbindaddr=0.0.0.0:5060
transport=tls,udp,tcp
srvlookup=yes
disallow=all
allow=ulaw
allow=alaw

externip=50.17.12.63
localnet=172.31.0.0/16

; --- CONFIGURACION DE SEGURIDAD TLS/SRTP ---
tlsenable=yes
tlsbindaddr=0.0.0.0:5061
tlscertfile=/etc/asterisk/keys/asterisk.pem
tlscafile=/etc/asterisk/keys/ca.crt
tlscipher=ALL
tlsclientmethod=tlsv1_2

; Configuración de la Extensión 100 
[100]
type=friend
host=dynamic
context=from-external  ; 
secret=clase2026       ; Esta será tu contraseña
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
transport=tls
encryption=yes

; Configuración de la Extensión 200
[200]
type=friend
host=dynamic
context=from-external
secret=clase2026
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
transport=tls
encryption=yes
