[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
; Aquí puedes definir variables globales si las necesitas en el futuro

; =========================================================
; CONTEXTO 1: LA POBLACIÓN (Extensiones 100 al 115)
; =========================================================
[poblacion]

; 1. Llamadas internas entre la población (Cualquier número del 100 al 115)
exten => _1XX,1,NoOp(Llamada interna de ${CALLERID(num)} hacia ${EXTEN})
same => n,Dial(PJSIP/${EXTEN},30) ; Cambiar PJSIP por SIP si usan sip.conf
same => n,Hangup()

; 2. Llamadas hacia la Central 1 (*111) -> AQUI ENTRA TU FILTRO SPAM
exten => *111,1,NoOp(El usuario ${CALLERID(num)} llama a la Central 1)
same => n,Answer()
; Ejecutamos tu script de Python pasándole el número de quien llama
same => n,AGI(/var/lib/asterisk/agi-bin/validador_central1.py,${CALLERID(num)})
; El script de Python devolverá una variable llamada ES_SPAM ("SI" o "NO")
same => n,GotoIf($["${ES_SPAM}" = "SI"]?rechazar:permitir)

; Ruta si ES SPAM
same => n(rechazar),NoOp(Bloqueado: El número está en la lista negra)
same => n,Hangup() ; Cuelga inmediatamente sin timbrar

; Ruta si NO ES SPAM
same => n(permitir),NoOp(Permitido: Timbrando en la Central 1)
; Asumimos que el asesor de la Central 1 usa la extensión 200 en su Zoiper
same => n,Dial(PJSIP/200,30) 
same => n,Hangup()

; 3. Llamadas hacia la Central 2 (*010) -> DENEGADO POR DISEÑO
exten => *010,1,NoOp(Intento bloqueado: La poblacion no puede llamar a Central 2)
same => n,Hangup()


; =========================================================
; CONTEXTO 2: LA CENTRAL 1 (El asesor que filtra)
; =========================================================
[central-1]

; 1. Puede llamar a la población (100 al 115)
exten => _1XX,1,Dial(PJSIP/${EXTEN},30)
same => n,Hangup()

; 2. Puede llamar a la Central 2 (*010) -> AQUI ENTRA EL MENÚ INTERACTIVO
exten => *010,1,NoOp(La Central 1 ingresa al menú de administración)
same => n,Answer()
; Ejecutamos tu script de Python para el menú IVR
same => n,AGI(/var/lib/asterisk/agi-bin/menu_central2.py)
same => n,Hangup()