[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0
tcpenable=no
transport=udp
srvlookup=yes
disallow=all
allow=ulaw
allow=alaw

; Configuración de la Extensión 100 
[100]
type=friend
host=dynamic
context=from-external  ; 
secret=clase2026       ; Esta será tu contraseña
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

; Configuración de la Extensión 200 (Para pruebas de SPAM)
[200]
type=friend
host=dynamic
context=from-external
secret=clase2026
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia

